version: '3.3'

services:
  app_ci:
#    env_file:
#      - .env
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    build: .
    image: fredcc/buzzbird_app_ci
    hostname: buzzbird_app_ci
    command: bash app.sh
#    network_mode: my-net

  worker_ci:
#    env_file:
#      - .env
    restart: always
    build: .
    image: fredcc/buzzbird_worker_ci
#    command: python3 manage.py qcluster
